[project]
name = "ee581"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "h5py>=3.13.0",
    "matplotlib>=3.10.0",
    "opencv-python>=4.11.0.86",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
